[build]
  command = "pnpm run build"
  publish = ".next"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ./package.json ./pnpm-lock.yaml"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "20"
  PNPM_VERSION = "10.7.0"

[[plugins]]
  package = "@netlify/plugin-nextjs" 